package subaraki.exsartagine;

import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.Mod.Instance;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.network.NetworkRegistry;
import subaraki.exsartagine.block.ExSartagineBlock;
import subaraki.exsartagine.gui.GuiHandler;
import subaraki.exsartagine.item.ExSartagineItems;
import subaraki.exsartagine.proxy.ServerProxy;
import subaraki.exsartagine.recipe.Recipes;
import subaraki.exsartagine.util.Reference;

import java.util.Arrays;

import static subaraki.exsartagine.util.Reference.MODID;

@Mod(name = Reference.NAME, modid = MODID, version = Reference.VERSION, dependencies = Reference.DEPENDENCY)
public class ExSartagine {

    @SidedProxy(serverSide = Reference.SERVER_PROXY , clientSide =Reference.CLIENT_PROXY)
    public static ServerProxy proxy;

    @Instance(Reference.MODID)
    public static ExSartagine instance;

    @EventHandler
    public void preInit(FMLPreInitializationEvent event){
        ModMetadata modMeta = event.getModMetadata();
        modMeta.authorList = Arrays.asList("Subaraki", "Isaac");
        modMeta.autogenerated = false;
        modMeta.credits = "";
        modMeta.description = "Thermo Efficient Pots and Pans";
        modMeta.url = "https://github.com/ArtixAllMighty/ExSartagine/wiki";
        instance = this;

        ExSartagineBlock.load();
        ExSartagineItems.load();

        proxy.registerTileEntityAndRenderer();
        proxy.registerRenders();

        NetworkRegistry.INSTANCE.registerGuiHandler(instance, new GuiHandler());

        new Recipes();

    }
}
